### ISSUE TITLE
文章小typo

### ISSUE THREAD

**Issue by JeffLuoo** [guoshijiang/cryptography#1]
https://github.com/guoshijiang/cryptography/blob/master/encryptType/README.md

对称加密
对称加密又称但密钥加密，整个加密过程中只使用一个密钥。所谓对称其实就是使用一把密钥加密，使用同一把密钥解密。对称加密由于加解和解密使用的是同一个密钥算法，故而在加解密的过程中速度比较快，适合于数据量比较大的加解密。

但密钥加密 -> 单？

**Comment by guoshijiang** [comment]
已解决
