### ISSUE TITLE
GitHub Pages 是否可以使用 Jekyll 等构建？

### ISSUE THREAD

**Issue by Ran-ying** [guoshijiang/cryptography#7]
通过 http://crypt.wenwoha.com/ 链接访问时所有超链接均指向 GitHub 仓库源文件而非网页。

或者说将 GitHub Pages 构建仓库与本仓库分离以继续保持该仓库结构？

同时可引入 KaTeX 或 MathJax 库以显示数学公式。

**Comment by guoshijiang** [comment]
可以帮忙一起做吗

**Comment by Ran-ying** [comment]
可以

**Comment by guoshijiang** [comment]
可以再帮忙调整一下目录结构吗，左边显示目录，右边显示内容，谢谢🙏

**Comment by Ran-ying** [comment]
是首页的目录结构吗，首页的内容是 README.md 的内容，那就需要修改 [README 文件](https://github.com/guoshijiang/cryptography/blob/master/README.md)了。

**Comment by guoshijiang** [comment]
可以修改的

**Comment by guoshijiang** [comment]
> 是首页的目录结构吗，首页的内容是 README.md 的内容，那就需要修改 [README 文件](https://github.com/guoshijiang/cryptography/blob/master/README.md)了。

可以修改

**Comment by guoshijiang** [comment]
你微信多少，我可以加一下你吗？

**Comment by guoshijiang** [comment]
我们有一个项目，邀请你加入

**Comment by Ran-ying** [comment]
我加你吧 是这个吗 LGZAXE
